<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $cities = [
            ['name' => 'Abriaquí','department_id' =>5],
            ['name' => 'Acacías','department_id' =>50],
            ['name' => 'Acandí','department_id' =>27],
            ['name' => 'Acevedo','department_id' =>41],
            ['name' => 'Achí','department_id' =>13],
            ['name' => 'Agrado','department_id' =>41],
            ['name' => 'Agua de Dios','department_id' =>25],
            ['name' => 'Aguachica','department_id' =>20],
            ['name' => 'Aguada','department_id' =>68],
            ['name' => 'Aguadas','department_id' =>17],
            ['name' => 'Aguazul','department_id' =>85],
            ['name' => 'Agustín Codazzi','department_id' =>20],
            ['name' => 'Aipe','department_id' =>41],
            ['name' => 'Albania','department_id' =>18],
            ['name' => 'Albania','department_id' =>44],
            ['name' => 'Albania','department_id' =>68],
            ['name' => 'Albán','department_id' =>25],
            ['name' => 'Albán (San José)','department_id' =>52],
            ['name' => 'Alcalá','department_id' =>76],
            ['name' => 'Alejandria','department_id' =>5],
            ['name' => 'Algarrobo','department_id' =>47],
            ['name' => 'Algeciras','department_id' =>41],
            ['name' => 'Almaguer','department_id' =>19],
            ['name' => 'Almeida','department_id' =>15],
            ['name' => 'Alpujarra','department_id' =>73],
            ['name' => 'Altamira','department_id' =>41],
            ['name' => 'Alto Baudó (Pie de Pato)','department_id' =>27],
            ['name' => 'Altos del Rosario','department_id' =>13],
            ['name' => 'Alvarado','department_id' =>73],
            ['name' => 'Amagá','department_id' =>5],
            ['name' => 'Amalfi','department_id' =>5],
            ['name' => 'Ambalema','department_id' =>73],
            ['name' => 'Anapoima','department_id' =>25],
            ['name' => 'Ancuya','department_id' =>52],
            ['name' => 'Andalucía','department_id' =>76],
            ['name' => 'Andes','department_id' =>5],
            ['name' => 'Angelópolis','department_id' =>5],
            ['name' => 'Angostura','department_id' =>5],
            ['name' => 'Anolaima','department_id' =>25],
            ['name' => 'Anorí','department_id' =>5],
            ['name' => 'Anserma','department_id' =>17],
            ['name' => 'Ansermanuevo','department_id' =>76],
            ['name' => 'Anzoátegui','department_id' =>73],
            ['name' => 'Anzá','department_id' =>5],
            ['name' => 'Apartadó','department_id' =>5],
            ['name' => 'Apulo','department_id' =>25],
            ['name' => 'Apía','department_id' =>66],
            ['name' => 'Aquitania','department_id' =>15],
            ['name' => 'Aracataca','department_id' =>47],
            ['name' => 'Aranzazu','department_id' =>17],
            ['name' => 'Aratoca','department_id' =>68],
            ['name' => 'Arauca','department_id' =>81],
            ['name' => 'Arauquita','department_id' =>81],
            ['name' => 'Arbeláez','department_id' =>25],
            ['name' => 'Arboleda (Berruecos)','department_id' =>52],
            ['name' => 'Arboledas','department_id' =>54],
            ['name' => 'Arboletes','department_id' =>5],
            ['name' => 'Arcabuco','department_id' =>15],
            ['name' => 'Arenal','department_id' =>13],
            ['name' => 'Argelia','department_id' =>5],
            ['name' => 'Argelia','department_id' =>19],
            ['name' => 'Argelia','department_id' =>76],
            ['name' => 'Ariguaní (El Difícil)','department_id' =>47],
            ['name' => 'Arjona','department_id' =>13],
            ['name' => 'Armenia','department_id' =>5],
            ['name' => 'Armenia','department_id' =>63],
            ['name' => 'Armero (Guayabal)','department_id' =>73],
            ['name' => 'Arroyohondo','department_id' =>13],
            ['name' => 'Astrea','department_id' =>20],
            ['name' => 'Ataco','department_id' =>73],
            ['name' => 'Atrato (Yuto)','department_id' =>27],
            ['name' => 'Ayapel','department_id' =>23],
            ['name' => 'Bagadó','department_id' =>27],
            ['name' => 'Bahía Solano (Mútis)','department_id' =>27],
            ['name' => 'Bajo Baudó (Pizarro)','department_id' =>27],
            ['name' => 'Balboa','department_id' =>19],
            ['name' => 'Balboa','department_id' =>66],
            ['name' => 'Baranoa','department_id' =>8],
            ['name' => 'Baraya','department_id' =>41],
            ['name' => 'Barbacoas','department_id' =>52],
            ['name' => 'Barbosa','department_id' =>5],
            ['name' => 'Barbosa','department_id' =>68],
            ['name' => 'Barichara','department_id' =>68],
            ['name' => 'Barranca de Upía','department_id' =>50],
            ['name' => 'Barrancabermeja','department_id' =>68],
            ['name' => 'Barrancas','department_id' =>44],
            ['name' => 'Barranco de Loba','department_id' =>13],
            ['name' => 'Barranquilla','department_id' =>8],
            ['name' => 'Becerríl','department_id' =>20],
            ['name' => 'Belalcázar','department_id' =>17],
            ['name' => 'Bello','department_id' =>5],
            ['name' => 'Belmira','department_id' =>5],
            ['name' => 'Beltrán','department_id' =>25],
            ['name' => 'Belén','department_id' =>15],
            ['name' => 'Belén','department_id' =>52],
            ['name' => 'Belén de Bajirá','department_id' =>27],
            ['name' => 'Belén de Umbría','department_id' =>66],
            ['name' => 'Belén de los Andaquíes','department_id' =>18],
            ['name' => 'Berbeo','department_id' =>15],
            ['name' => 'Betania','department_id' =>5],
            ['name' => 'Beteitiva','department_id' =>15],
            ['name' => 'Betulia','department_id' =>5],
            ['name' => 'Betulia','department_id' =>68],
            ['name' => 'Bituima','department_id' =>25],
            ['name' => 'Boavita','department_id' =>15],
            ['name' => 'Bochalema','department_id' =>54],
            ['name' => 'Bogotá D.C.','department_id' =>11],
            ['name' => 'Bojacá','department_id' =>25],
            ['name' => 'Bojayá (Bellavista)','department_id' =>27],
            ['name' => 'Bolívar','department_id' =>5],
            ['name' => 'Bolívar','department_id' =>19],
            ['name' => 'Bolívar','department_id' =>68],
            ['name' => 'Bolívar','department_id' =>76],
            ['name' => 'Bosconia','department_id' =>20],
            ['name' => 'Boyacá','department_id' =>15],
            ['name' => 'Briceño','department_id' =>5],
            ['name' => 'Briceño','department_id' =>15],
            ['name' => 'Bucaramanga','department_id' =>68],
            ['name' => 'Bucarasica','department_id' =>54],
            ['name' => 'Buenaventura','department_id' =>76],
            ['name' => 'Buenavista','department_id' =>15],
            ['name' => 'Buenavista','department_id' =>23],
            ['name' => 'Buenavista','department_id' =>63],
            ['name' => 'Buenavista','department_id' =>70],
            ['name' => 'Buenos Aires','department_id' =>19],
            ['name' => 'Buesaco','department_id' =>52],
            ['name' => 'Buga','department_id' =>76],
            ['name' => 'Bugalagrande','department_id' =>76],
            ['name' => 'Burítica','department_id' =>5],
            ['name' => 'Busbanza','department_id' =>15],
            ['name' => 'Cabrera','department_id' =>25],
            ['name' => 'Cabrera','department_id' =>68],
            ['name' => 'Cabuyaro','department_id' =>50],
            ['name' => 'Cachipay','department_id' =>25],
            ['name' => 'Caicedo','department_id' =>5],
            ['name' => 'Caicedonia','department_id' =>76],
            ['name' => 'Caimito','department_id' =>70],
            ['name' => 'Cajamarca','department_id' =>73],
            ['name' => 'Cajibío','department_id' =>19],
            ['name' => 'Cajicá','department_id' =>25],
            ['name' => 'Calamar','department_id' =>13],
            ['name' => 'Calamar','department_id' =>95],
            ['name' => 'Calarcá','department_id' =>63],
            ['name' => 'Caldas','department_id' =>5],
            ['name' => 'Caldas','department_id' =>15],
            ['name' => 'Caldono','department_id' =>19],
            ['name' => 'California','department_id' =>68],
            ['name' => 'Calima (Darién)','department_id' =>76],
            ['name' => 'Caloto','department_id' =>19],
            ['name' => 'Calí','department_id' =>76],
            ['name' => 'Campamento','department_id' =>5],
            ['name' => 'Campo de la Cruz','department_id' =>8],
            ['name' => 'Campoalegre','department_id' =>41],
            ['name' => 'Campohermoso','department_id' =>15],
            ['name' => 'Canalete','department_id' =>23],
            ['name' => 'Candelaria','department_id' =>8],
            ['name' => 'Candelaria','department_id' =>76],
            ['name' => 'Cantagallo','department_id' =>13],
            ['name' => 'Cantón de San Pablo','department_id' =>27],
            ['name' => 'Caparrapí','department_id' =>25],
            ['name' => 'Capitanejo','department_id' =>68],
            ['name' => 'Caracolí','department_id' =>5],
            ['name' => 'Caramanta','department_id' =>5],
            ['name' => 'Carcasí','department_id' =>68],
            ['name' => 'Carepa','department_id' =>5],
            ['name' => 'Carmen de Apicalá','department_id' =>73],
            ['name' => 'Carmen de Carupa','department_id' =>25],
            ['name' => 'Carmen de Viboral','department_id' =>5],
            ['name' => 'Carmen del Darién (CURBARADÓ)','department_id' =>27],
            ['name' => 'Carolina','department_id' =>5],
            ['name' => 'Cartagena','department_id' =>13],
            ['name' => 'Cartagena del Chairá','department_id' =>18],
            ['name' => 'Cartago','department_id' =>76],
            ['name' => 'Carurú','department_id' =>97],
            ['name' => 'Casabianca','department_id' =>73],
            ['name' => 'Castilla la Nueva','department_id' =>50],
            ['name' => 'Caucasia','department_id' =>5],
            ['name' => 'Cañasgordas','department_id' =>5],
            ['name' => 'Cepita','department_id' =>68],
            ['name' => 'Cereté','department_id' =>23],
            ['name' => 'Cerinza','department_id' =>15],
            ['name' => 'Cerrito','department_id' =>68],
            ['name' => 'Cerro San Antonio','department_id' =>47],
            ['name' => 'Chachaguí','department_id' =>52],
            ['name' => 'Chaguaní','department_id' =>25],
            ['name' => 'Chalán','department_id' =>70],
            ['name' => 'Chaparral','department_id' =>73],
            ['name' => 'Charalá','department_id' =>68],
            ['name' => 'Charta','department_id' =>68],
            ['name' => 'Chigorodó','department_id' =>5],
            ['name' => 'Chima','department_id' =>68],
            ['name' => 'Chimichagua','department_id' =>20],
            ['name' => 'Chimá','department_id' =>23],
            ['name' => 'Chinavita','department_id' =>15],
            ['name' => 'Chinchiná','department_id' =>17],
            ['name' => 'Chinácota','department_id' =>54],
            ['name' => 'Chinú','department_id' =>23],
            ['name' => 'Chipaque','department_id' =>25],
            ['name' => 'Chipatá','department_id' =>68],
            ['name' => 'Chiquinquirá','department_id' =>15],
            ['name' => 'Chiriguaná','department_id' =>20],
            ['name' => 'Chiscas','department_id' =>15],
            ['name' => 'Chita','department_id' =>15],
            ['name' => 'Chitagá','department_id' =>54],
            ['name' => 'Chitaraque','department_id' =>15],
            ['name' => 'Chivatá','department_id' =>15],
            ['name' => 'Chivolo','department_id' =>47],
            ['name' => 'Choachí','department_id' =>25],
            ['name' => 'Chocontá','department_id' =>25],
            ['name' => 'Chámeza','department_id' =>85],
            ['name' => 'Chía','department_id' =>25],
            ['name' => 'Chíquiza','department_id' =>15],
            ['name' => 'Chívor','department_id' =>15],
            ['name' => 'Cicuco','department_id' =>13],
            ['name' => 'Cimitarra','department_id' =>68],
            ['name' => 'Circasia','department_id' =>63],
            ['name' => 'Cisneros','department_id' =>5],
            ['name' => 'Ciénaga','department_id' =>15],
            ['name' => 'Ciénaga','department_id' =>47],
            ['name' => 'Ciénaga de Oro','department_id' =>23],
            ['name' => 'Clemencia','department_id' =>13],
            ['name' => 'Cocorná','department_id' =>5],
            ['name' => 'Coello','department_id' =>73],
            ['name' => 'Cogua','department_id' =>25],
            ['name' => 'Colombia','department_id' =>41],
            ['name' => 'Colosó (Ricaurte)','department_id' =>70],
            ['name' => 'Colón','department_id' =>86],
            ['name' => 'Colón (Génova)','department_id' =>52],
            ['name' => 'Concepción','department_id' =>5],
            ['name' => 'Concepción','department_id' =>68],
            ['name' => 'Concordia','department_id' =>5],
            ['name' => 'Concordia','department_id' =>47],
            ['name' => 'Condoto','department_id' =>27],
            ['name' => 'Confines','department_id' =>68],
            ['name' => 'Consaca','department_id' =>52],
            ['name' => 'Contadero','department_id' =>52],
            ['name' => 'Contratación','department_id' =>68],
            ['name' => 'Convención','department_id' =>54],
            ['name' => 'Copacabana','department_id' =>5],
            ['name' => 'Coper','department_id' =>15],
            ['name' => 'Cordobá','department_id' =>63],
            ['name' => 'Corinto','department_id' =>19],
            ['name' => 'Coromoro','department_id' =>68],
            ['name' => 'Corozal','department_id' =>70],
            ['name' => 'Corrales','department_id' =>15],
            ['name' => 'Cota','department_id' =>25],
            ['name' => 'Cotorra','department_id' =>23],
            ['name' => 'Covarachía','department_id' =>15],
            ['name' => 'Coveñas','department_id' =>70],
            ['name' => 'Coyaima','department_id' =>73],
            ['name' => 'Cravo Norte','department_id' =>81],
            ['name' => 'Cuaspud (Carlosama)','department_id' =>52],
            ['name' => 'Cubarral','department_id' =>50],
            ['name' => 'Cubará','department_id' =>15],
            ['name' => 'Cucaita','department_id' =>15],
            ['name' => 'Cucunubá','department_id' =>25],
            ['name' => 'Cucutilla','department_id' =>54],
            ['name' => 'Cuitiva','department_id' =>15],
            ['name' => 'Cumaral','department_id' =>50],
            ['name' => 'Cumaribo','department_id' =>99],
            ['name' => 'Cumbal','department_id' =>52],
            ['name' => 'Cumbitara','department_id' =>52],
            ['name' => 'Cunday','department_id' =>73],
            ['name' => 'Curillo','department_id' =>18],
            ['name' => 'Curití','department_id' =>68],
            ['name' => 'Curumaní','department_id' =>20],
            ['name' => 'Cáceres','department_id' =>5],
            ['name' => 'Cáchira','department_id' =>54],
            ['name' => 'Cácota','department_id' =>54],
            ['name' => 'Cáqueza','department_id' =>25],
            ['name' => 'Cértegui','department_id' =>27],
            ['name' => 'Cómbita','department_id' =>15],
            ['name' => 'Córdoba','department_id' =>13],
            ['name' => 'Córdoba','department_id' =>52],
            ['name' => 'Cúcuta','department_id' =>54],
            ['name' => 'Dabeiba','department_id' =>5],
            ['name' => 'Dagua','department_id' =>76],
            ['name' => 'Dibulla','department_id' =>44],
            ['name' => 'Distracción','department_id' =>44],
            ['name' => 'Dolores','department_id' =>73],
            ['name' => 'Don Matías','department_id' =>5],
            ['name' => 'Dos Quebradas','department_id' =>66],
            ['name' => 'Duitama','department_id' =>15],
            ['name' => 'Durania','department_id' =>54],
            ['name' => 'Ebéjico','department_id' =>5],
            ['name' => 'El Bagre','department_id' =>5],
            ['name' => 'El Banco','department_id' =>47],
            ['name' => 'El Cairo','department_id' =>76],
            ['name' => 'El Calvario','department_id' =>50],
            ['name' => 'El Carmen','department_id' =>54],
            ['name' => 'El Carmen','department_id' =>68],
            ['name' => 'El Carmen de Atrato','department_id' =>27],
            ['name' => 'El Carmen de Bolívar','department_id' =>13],
            ['name' => 'El Castillo','department_id' =>50],
            ['name' => 'El Cerrito','department_id' =>76],
            ['name' => 'El Charco','department_id' =>52],
            ['name' => 'El Cocuy','department_id' =>15],
            ['name' => 'El Colegio','department_id' =>25],
            ['name' => 'El Copey','department_id' =>20],
            ['name' => 'El Doncello','department_id' =>18],
            ['name' => 'El Dorado','department_id' =>50],
            ['name' => 'El Dovio','department_id' =>76],
            ['name' => 'El Espino','department_id' =>15],
            ['name' => 'El Guacamayo','department_id' =>68],
            ['name' => 'El Guamo','department_id' =>13],
            ['name' => 'El Molino','department_id' =>44],
            ['name' => 'El Paso','department_id' =>20],
            ['name' => 'El Paujil','department_id' =>18],
            ['name' => 'El Peñol','department_id' =>52],
            ['name' => 'El Peñon','department_id' =>13],
            ['name' => 'El Peñon','department_id' =>68],
            ['name' => 'El Peñón','department_id' =>25],
            ['name' => 'El Piñon','department_id' =>47],
            ['name' => 'El Playón','department_id' =>68],
            ['name' => 'El Retorno','department_id' =>95],
            ['name' => 'El Retén','department_id' =>47],
            ['name' => 'El Roble','department_id' =>70],
            ['name' => 'El Rosal','department_id' =>25],
            ['name' => 'El Rosario','department_id' =>52],
            ['name' => 'El Tablón de Gómez','department_id' =>52],
            ['name' => 'El Tambo','department_id' =>19],
            ['name' => 'El Tambo','department_id' =>52],
            ['name' => 'El Tarra','department_id' =>54],
            ['name' => 'El Zulia','department_id' =>54],
            ['name' => 'El Águila','department_id' =>76],
            ['name' => 'Elías','department_id' =>41],
            ['name' => 'Encino','department_id' =>68],
            ['name' => 'Enciso','department_id' =>68],
            ['name' => 'Entrerríos','department_id' =>5],
            ['name' => 'Envigado','department_id' =>5],
            ['name' => 'Espinal','department_id' =>73],
            ['name' => 'Facatativá','department_id' =>25],
            ['name' => 'Falan','department_id' =>73],
            ['name' => 'Filadelfia','department_id' =>17],
            ['name' => 'Filandia','department_id' =>63],
            ['name' => 'Firavitoba','department_id' =>15],
            ['name' => 'Flandes','department_id' =>73],
            ['name' => 'Florencia','department_id' =>18],
            ['name' => 'Florencia','department_id' =>19],
            ['name' => 'Floresta','department_id' =>15],
            ['name' => 'Florida','department_id' =>76],
            ['name' => 'Floridablanca','department_id' =>68],
            ['name' => 'Florián','department_id' =>68],
            ['name' => 'Fonseca','department_id' =>44],
            ['name' => 'Fortúl','department_id' =>81],
            ['name' => 'Fosca','department_id' =>25],
            ['name' => 'Francisco Pizarro','department_id' =>52],
            ['name' => 'Fredonia','department_id' =>5],
            ['name' => 'Fresno','department_id' =>73],
            ['name' => 'Frontino','department_id' =>5],
            ['name' => 'Fuente de Oro','department_id' =>50],
            ['name' => 'Fundación','department_id' =>47],
            ['name' => 'Funes','department_id' =>52],
            ['name' => 'Funza','department_id' =>25],
            ['name' => 'Fusagasugá','department_id' =>25],
            ['name' => 'Fómeque','department_id' =>25],
            ['name' => 'Fúquene','department_id' =>25],
            ['name' => 'Gachalá','department_id' =>25],
            ['name' => 'Gachancipá','department_id' =>25],
            ['name' => 'Gachantivá','department_id' =>15],
            ['name' => 'Gachetá','department_id' =>25],
            ['name' => 'Galapa','department_id' =>8],
            ['name' => 'Galeras (Nueva Granada)','department_id' =>70],
            ['name' => 'Galán','department_id' =>68],
            ['name' => 'Gama','department_id' =>25],
            ['name' => 'Gamarra','department_id' =>20],
            ['name' => 'Garagoa','department_id' =>15],
            ['name' => 'Garzón','department_id' =>41],
            ['name' => 'Gigante','department_id' =>41],
            ['name' => 'Ginebra','department_id' =>76],
            ['name' => 'Giraldo','department_id' =>5],
            ['name' => 'Girardot','department_id' =>25],
            ['name' => 'Girardota','department_id' =>5],
            ['name' => 'Girón','department_id' =>68],
            ['name' => 'Gonzalez','department_id' =>20],
            ['name' => 'Gramalote','department_id' =>54],
            ['name' => 'Granada','department_id' =>5],
            ['name' => 'Granada','department_id' =>25],
            ['name' => 'Granada','department_id' =>50],
            ['name' => 'Guaca','department_id' =>68],
            ['name' => 'Guacamayas','department_id' =>15],
            ['name' => 'Guacarí','department_id' =>76],
            ['name' => 'Guachavés','department_id' =>52],
            ['name' => 'Guachené','department_id' =>19],
            ['name' => 'Guachetá','department_id' =>25],
            ['name' => 'Guachucal','department_id' =>52],
            ['name' => 'Guadalupe','department_id' =>5],
            ['name' => 'Guadalupe','department_id' =>41],
            ['name' => 'Guadalupe','department_id' =>68],
            ['name' => 'Guaduas','department_id' =>25],
            ['name' => 'Guaitarilla','department_id' =>52],
            ['name' => 'Gualmatán','department_id' =>52],
            ['name' => 'Guamal','department_id' =>47],
            ['name' => 'Guamal','department_id' =>50],
            ['name' => 'Guamo','department_id' =>73],
            ['name' => 'Guapota','department_id' =>68],
            ['name' => 'Guapí','department_id' =>19],
            ['name' => 'Guaranda','department_id' =>70],
            ['name' => 'Guarne','department_id' =>5],
            ['name' => 'Guasca','department_id' =>25],
            ['name' => 'Guatapé','department_id' =>5],
            ['name' => 'Guataquí','department_id' =>25],
            ['name' => 'Guatavita','department_id' =>25],
            ['name' => 'Guateque','department_id' =>15],
            ['name' => 'Guavatá','department_id' =>68],
            ['name' => 'Guayabal de Siquima','department_id' =>25],
            ['name' => 'Guayabetal','department_id' =>25],
            ['name' => 'Guayatá','department_id' =>15],
            ['name' => 'Guepsa','department_id' =>68],
            ['name' => 'Guicán','department_id' =>15],
            ['name' => 'Gutiérrez','department_id' =>25],
            ['name' => 'Guática','department_id' =>66],
            ['name' => 'Gámbita','department_id' =>68],
            ['name' => 'Gámeza','department_id' =>15],
            ['name' => 'Génova','department_id' =>63],
            ['name' => 'Gómez Plata','department_id' =>5],
            ['name' => 'Hacarí','department_id' =>54],
            ['name' => 'Hatillo de Loba','department_id' =>13],
            ['name' => 'Hato','department_id' =>68],
            ['name' => 'Hato Corozal','department_id' =>85],
            ['name' => 'Hatonuevo','department_id' =>44],
            ['name' => 'Heliconia','department_id' =>5],
            ['name' => 'Herrán','department_id' =>54],
            ['name' => 'Herveo','department_id' =>73],
            ['name' => 'Hispania','department_id' =>5],
            ['name' => 'Hobo','department_id' =>41],
            ['name' => 'Honda','department_id' =>73],
            ['name' => 'Ibagué','department_id' =>73],
            ['name' => 'Icononzo','department_id' =>73],
            ['name' => 'Iles','department_id' =>52],
            ['name' => 'Imúes','department_id' =>52],
            ['name' => 'Inzá','department_id' =>19],
            ['name' => 'Inírida','department_id' =>94],
            ['name' => 'Ipiales','department_id' =>52],
            ['name' => 'Isnos','department_id' =>41],
            ['name' => 'Istmina','department_id' =>27],
            ['name' => 'Itagüí','department_id' =>5],
            ['name' => 'Ituango','department_id' =>5],
            ['name' => 'Izá','department_id' =>15],
            ['name' => 'Jambaló','department_id' =>19],
            ['name' => 'Jamundí','department_id' =>76],
            ['name' => 'Jardín','department_id' =>5],
            ['name' => 'Jenesano','department_id' =>15],
            ['name' => 'Jericó','department_id' =>5],
            ['name' => 'Jericó','department_id' =>15],
            ['name' => 'Jerusalén','department_id' =>25],
            ['name' => 'Jesús María','department_id' =>68],
            ['name' => 'Jordán','department_id' =>68],
            ['name' => 'Juan de Acosta','department_id' =>8],
            ['name' => 'Junín','department_id' =>25],
            ['name' => 'Juradó','department_id' =>27],
            ['name' => 'La Apartada y La Frontera','department_id' =>23],
            ['name' => 'La Argentina','department_id' =>41],
            ['name' => 'La Belleza','department_id' =>68],
            ['name' => 'La Calera','department_id' =>25],
            ['name' => 'La Capilla','department_id' =>15],
            ['name' => 'La Ceja','department_id' =>5],
            ['name' => 'La Celia','department_id' =>66],
            ['name' => 'La Cruz','department_id' =>52],
            ['name' => 'La Cumbre','department_id' =>76],
            ['name' => 'La Dorada','department_id' =>17],
            ['name' => 'La Esperanza','department_id' =>54],
            ['name' => 'La Estrella','department_id' =>5],
            ['name' => 'La Florida','department_id' =>52],
            ['name' => 'La Gloria','department_id' =>20],
            ['name' => 'La Jagua de Ibirico','department_id' =>20],
            ['name' => 'La Jagua del Pilar','department_id' =>44],
            ['name' => 'La Llanada','department_id' =>52],
            ['name' => 'La Macarena','department_id' =>50],
            ['name' => 'La Merced','department_id' =>17],
            ['name' => 'La Mesa','department_id' =>25],
            ['name' => 'La Montañita','department_id' =>18],
            ['name' => 'La Palma','department_id' =>25],
            ['name' => 'La Paz','department_id' =>68],
            ['name' => 'La Paz (Robles)','department_id' =>20],
            ['name' => 'La Peña','department_id' =>25],
            ['name' => 'La Pintada','department_id' =>5],
            ['name' => 'La Plata','department_id' =>41],
            ['name' => 'La Playa','department_id' =>54],
            ['name' => 'La Primavera','department_id' =>99],
            ['name' => 'La Salina','department_id' =>85],
            ['name' => 'La Sierra','department_id' =>19],
            ['name' => 'La Tebaida','department_id' =>63],
            ['name' => 'La Tola','department_id' =>52],
            ['name' => 'La Unión','department_id' =>5],
            ['name' => 'La Unión','department_id' =>52],
            ['name' => 'La Unión','department_id' =>70],
            ['name' => 'La Unión','department_id' =>76],
            ['name' => 'La Uvita','department_id' =>15],
            ['name' => 'La Vega','department_id' =>19],
            ['name' => 'La Vega','department_id' =>25],
            ['name' => 'La Victoria','department_id' =>15],
            ['name' => 'La Victoria','department_id' =>17],
            ['name' => 'La Victoria','department_id' =>76],
            ['name' => 'La Virginia','department_id' =>66],
            ['name' => 'Labateca','department_id' =>54],
            ['name' => 'Labranzagrande','department_id' =>15],
            ['name' => 'Landázuri','department_id' =>68],
            ['name' => 'Lebrija','department_id' =>68],
            ['name' => 'Leiva','department_id' =>52],
            ['name' => 'Lejanías','department_id' =>50],
            ['name' => 'Lenguazaque','department_id' =>25],
            ['name' => 'Leticia','department_id' =>91],
            ['name' => 'Liborina','department_id' =>5],
            ['name' => 'Linares','department_id' =>52],
            ['name' => 'Lloró','department_id' =>27],
            ['name' => 'Lorica','department_id' =>23],
            ['name' => 'Los Córdobas','department_id' =>23],
            ['name' => 'Los Palmitos','department_id' =>70],
            ['name' => 'Los Patios','department_id' =>54],
            ['name' => 'Los Santos','department_id' =>68],
            ['name' => 'Lourdes','department_id' =>54],
            ['name' => 'Luruaco','department_id' =>8],
            ['name' => 'Lérida','department_id' =>73],
            ['name' => 'Líbano','department_id' =>73],
            ['name' => 'López (Micay)','department_id' =>19],
            ['name' => 'Macanal','department_id' =>15],
            ['name' => 'Macaravita','department_id' =>68],
            ['name' => 'Maceo','department_id' =>5],
            ['name' => 'Machetá','department_id' =>25],
            ['name' => 'Madrid','department_id' =>25],
            ['name' => 'Magangué','department_id' =>13],
            ['name' => 'Magüi (Payán)','department_id' =>52],
            ['name' => 'Mahates','department_id' =>13],
            ['name' => 'Maicao','department_id' =>44],
            ['name' => 'Majagual','department_id' =>70],
            ['name' => 'Malambo','department_id' =>8],
            ['name' => 'Mallama (Piedrancha)','department_id' =>52],
            ['name' => 'Manatí','department_id' =>8],
            ['name' => 'Manaure','department_id' =>44],
            ['name' => 'Manaure Balcón del Cesar','department_id' =>20],
            ['name' => 'Manizales','department_id' =>17],
            ['name' => 'Manta','department_id' =>25],
            ['name' => 'Manzanares','department_id' =>17],
            ['name' => 'Maní','department_id' =>85],
            ['name' => 'Mapiripan','department_id' =>50],
            ['name' => 'Margarita','department_id' =>13],
            ['name' => 'Marinilla','department_id' =>5],
            ['name' => 'Maripí','department_id' =>15],
            ['name' => 'Mariquita','department_id' =>73],
            ['name' => 'Marmato','department_id' =>17],
            ['name' => 'Marquetalia','department_id' =>17],
            ['name' => 'Marsella','department_id' =>66],
            ['name' => 'Marulanda','department_id' =>17],
            ['name' => 'María la Baja','department_id' =>13],
            ['name' => 'Matanza','department_id' =>68],
            ['name' => 'Medellín','department_id' =>5],
            ['name' => 'Medina','department_id' =>25],
            ['name' => 'Medio Atrato','department_id' =>27],
            ['name' => 'Medio Baudó','department_id' =>27],
            ['name' => 'Medio San Juan (ANDAGOYA)','department_id' =>27],
            ['name' => 'Melgar','department_id' =>73],
            ['name' => 'Mercaderes','department_id' =>19],
            ['name' => 'Mesetas','department_id' =>50],
            ['name' => 'Milán','department_id' =>18],
            ['name' => 'Miraflores','department_id' =>15],
            ['name' => 'Miraflores','department_id' =>95],
            ['name' => 'Miranda','department_id' =>19],
            ['name' => 'Mistrató','department_id' =>66],
            ['name' => 'Mitú','department_id' =>97],
            ['name' => 'Mocoa','department_id' =>86],
            ['name' => 'Mogotes','department_id' =>68],
            ['name' => 'Molagavita','department_id' =>68],
            ['name' => 'Momil','department_id' =>23],
            ['name' => 'Mompós','department_id' =>13],
            ['name' => 'Mongua','department_id' =>15],
            ['name' => 'Monguí','department_id' =>15],
            ['name' => 'Moniquirá','department_id' =>15],
            ['name' => 'Montebello','department_id' =>5],
            ['name' => 'Montecristo','department_id' =>13],
            ['name' => 'Montelíbano','department_id' =>23],
            ['name' => 'Montenegro','department_id' =>63],
            ['name' => 'Monteria','department_id' =>23],
            ['name' => 'Monterrey','department_id' =>85],
            ['name' => 'Morales','department_id' =>13],
            ['name' => 'Morales','department_id' =>19],
            ['name' => 'Morelia','department_id' =>18],
            ['name' => 'Morroa','department_id' =>70],
            ['name' => 'Mosquera','department_id' =>25],
            ['name' => 'Mosquera','department_id' =>52],
            ['name' => 'Motavita','department_id' =>15],
            ['name' => 'Moñitos','department_id' =>23],
            ['name' => 'Murillo','department_id' =>73],
            ['name' => 'Murindó','department_id' =>5],
            ['name' => 'Mutatá','department_id' =>5],
            ['name' => 'Mutiscua','department_id' =>54],
            ['name' => 'Muzo','department_id' =>15],
            ['name' => 'Málaga','department_id' =>68],
            ['name' => 'Nariño','department_id' =>5],
            ['name' => 'Nariño','department_id' =>25],
            ['name' => 'Nariño','department_id' =>52],
            ['name' => 'Natagaima','department_id' =>73],
            ['name' => 'Nechí','department_id' =>5],
            ['name' => 'Necoclí','department_id' =>5],
            ['name' => 'Neira','department_id' =>17],
            ['name' => 'Neiva','department_id' =>41],
            ['name' => 'Nemocón','department_id' =>25],
            ['name' => 'Nilo','department_id' =>25],
            ['name' => 'Nimaima','department_id' =>25],
            ['name' => 'Nobsa','department_id' =>15],
            ['name' => 'Nocaima','department_id' =>25],
            ['name' => 'Norcasia','department_id' =>17],
            ['name' => 'Norosí','department_id' =>13],
            ['name' => 'Novita','department_id' =>27],
            ['name' => 'Nueva Granada','department_id' =>47],
            ['name' => 'Nuevo Colón','department_id' =>15],
            ['name' => 'Nunchía','department_id' =>85],
            ['name' => 'Nuquí','department_id' =>27],
            ['name' => 'Nátaga','department_id' =>41],
            ['name' => 'Obando','department_id' =>76],
            ['name' => 'Ocamonte','department_id' =>68],
            ['name' => 'Ocaña','department_id' =>54],
            ['name' => 'Oiba','department_id' =>68],
            ['name' => 'Oicatá','department_id' =>15],
            ['name' => 'Olaya','department_id' =>5],
            ['name' => 'Olaya Herrera','department_id' =>52],
            ['name' => 'Onzaga','department_id' =>68],
            ['name' => 'Oporapa','department_id' =>41],
            ['name' => 'Orito','department_id' =>86],
            ['name' => 'Orocué','department_id' =>85],
            ['name' => 'Ortega','department_id' =>73],
            ['name' => 'Ospina','department_id' =>52],
            ['name' => 'Otanche','department_id' =>15],
            ['name' => 'Ovejas','department_id' =>70],
            ['name' => 'Pachavita','department_id' =>15],
            ['name' => 'Pacho','department_id' =>25],
            ['name' => 'Padilla','department_id' =>19],
            ['name' => 'Paicol','department_id' =>41],
            ['name' => 'Pailitas','department_id' =>20],
            ['name' => 'Paime','department_id' =>25],
            ['name' => 'Paipa','department_id' =>15],
            ['name' => 'Pajarito','department_id' =>15],
            ['name' => 'Palermo','department_id' =>41],
            ['name' => 'Palestina','department_id' =>17],
            ['name' => 'Palestina','department_id' =>41],
            ['name' => 'Palmar','department_id' =>68],
            ['name' => 'Palmar de Varela','department_id' =>8],
            ['name' => 'Palmas del Socorro','department_id' =>68],
            ['name' => 'Palmira','department_id' =>76],
            ['name' => 'Palmito','department_id' =>70],
            ['name' => 'Palocabildo','department_id' =>73],
            ['name' => 'Pamplona','department_id' =>54],
            ['name' => 'Pamplonita','department_id' =>54],
            ['name' => 'Pandi','department_id' =>25],
            ['name' => 'Panqueba','department_id' =>15],
            ['name' => 'Paratebueno','department_id' =>25],
            ['name' => 'Pasca','department_id' =>25],
            ['name' => 'Patía (El Bordo)','department_id' =>19],
            ['name' => 'Pauna','department_id' =>15],
            ['name' => 'Paya','department_id' =>15],
            ['name' => 'Paz de Ariporo','department_id' =>85],
            ['name' => 'Paz de Río','department_id' =>15],
            ['name' => 'Pedraza','department_id' =>47],
            ['name' => 'Pelaya','department_id' =>20],
            ['name' => 'Pensilvania','department_id' =>17],
            ['name' => 'Peque','department_id' =>5],
            ['name' => 'Pereira','department_id' =>66],
            ['name' => 'Pesca','department_id' =>15],
            ['name' => 'Peñol','department_id' =>5],
            ['name' => 'Piamonte','department_id' =>19],
            ['name' => 'Pie de Cuesta','department_id' =>68],
            ['name' => 'Piedras','department_id' =>73],
            ['name' => 'Piendamó','department_id' =>19],
            ['name' => 'Pijao','department_id' =>63],
            ['name' => 'Pijiño','department_id' =>47],
            ['name' => 'Pinchote','department_id' =>68],
            ['name' => 'Pinillos','department_id' =>13],
            ['name' => 'Piojo','department_id' =>8],
            ['name' => 'Pisva','department_id' =>15],
            ['name' => 'Pital','department_id' =>41],
            ['name' => 'Pitalito','department_id' =>41],
            ['name' => 'Pivijay','department_id' =>47],
            ['name' => 'Planadas','department_id' =>73],
            ['name' => 'Planeta Rica','department_id' =>23],
            ['name' => 'Plato','department_id' =>47],
            ['name' => 'Policarpa','department_id' =>52],
            ['name' => 'Polonuevo','department_id' =>8],
            ['name' => 'Ponedera','department_id' =>8],
            ['name' => 'Popayán','department_id' =>19],
            ['name' => 'Pore','department_id' =>85],
            ['name' => 'Potosí','department_id' =>52],
            ['name' => 'Pradera','department_id' =>76],
            ['name' => 'Prado','department_id' =>73],
            ['name' => 'Providencia','department_id' =>52],
            ['name' => 'Providencia','department_id' =>88],
            ['name' => 'Pueblo Bello','department_id' =>20],
            ['name' => 'Pueblo Nuevo','department_id' =>23],
            ['name' => 'Pueblo Rico','department_id' =>66],
            ['name' => 'Pueblorrico','department_id' =>5],
            ['name' => 'Puebloviejo','department_id' =>47],
            ['name' => 'Puente Nacional','department_id' =>68],
            ['name' => 'Puerres','department_id' =>52],
            ['name' => 'Puerto Asís','department_id' =>86],
            ['name' => 'Puerto Berrío','department_id' =>5],
            ['name' => 'Puerto Boyacá','department_id' =>15],
            ['name' => 'Puerto Caicedo','department_id' =>86],
            ['name' => 'Puerto Carreño','department_id' =>99],
            ['name' => 'Puerto Colombia','department_id' =>8],
            ['name' => 'Puerto Concordia','department_id' =>50],
            ['name' => 'Puerto Escondido','department_id' =>23],
            ['name' => 'Puerto Gaitán','department_id' =>50],
            ['name' => 'Puerto Guzmán','department_id' =>86],
            ['name' => 'Puerto Leguízamo','department_id' =>86],
            ['name' => 'Puerto Libertador','department_id' =>23],
            ['name' => 'Puerto Lleras','department_id' =>50],
            ['name' => 'Puerto López','department_id' =>50],
            ['name' => 'Puerto Nare','department_id' =>5],
            ['name' => 'Puerto Nariño','department_id' =>91],
            ['name' => 'Puerto Parra','department_id' =>68],
            ['name' => 'Puerto Rico','department_id' =>18],
            ['name' => 'Puerto Rico','department_id' =>50],
            ['name' => 'Puerto Rondón','department_id' =>81],
            ['name' => 'Puerto Salgar','department_id' =>25],
            ['name' => 'Puerto Santander','department_id' =>54],
            ['name' => 'Puerto Tejada','department_id' =>19],
            ['name' => 'Puerto Triunfo','department_id' =>5],
            ['name' => 'Puerto Wilches','department_id' =>68],
            ['name' => 'Pulí','department_id' =>25],
            ['name' => 'Pupiales','department_id' =>52],
            ['name' => 'Puracé (Coconuco)','department_id' =>19],
            ['name' => 'Purificación','department_id' =>73],
            ['name' => 'Purísima','department_id' =>23],
            ['name' => 'Pácora','department_id' =>17],
            ['name' => 'Páez','department_id' =>15],
            ['name' => 'Páez (Belalcazar)','department_id' =>19],
            ['name' => 'Páramo','department_id' =>68],
            ['name' => 'Quebradanegra','department_id' =>25],
            ['name' => 'Quetame','department_id' =>25],
            ['name' => 'Quibdó','department_id' =>27],
            ['name' => 'Quimbaya','department_id' =>63],
            ['name' => 'Quinchía','department_id' =>66],
            ['name' => 'Quipama','department_id' =>15],
            ['name' => 'Quipile','department_id' =>25],
            ['name' => 'Ragonvalia','department_id' =>54],
            ['name' => 'Ramiriquí','department_id' =>15],
            ['name' => 'Recetor','department_id' =>85],
            ['name' => 'Regidor','department_id' =>13],
            ['name' => 'Remedios','department_id' =>5],
            ['name' => 'Remolino','department_id' =>47],
            ['name' => 'Repelón','department_id' =>8],
            ['name' => 'Restrepo','department_id' =>50],
            ['name' => 'Restrepo','department_id' =>76],
            ['name' => 'Retiro','department_id' =>5],
            ['name' => 'Ricaurte','department_id' =>25],
            ['name' => 'Ricaurte','department_id' =>52],
            ['name' => 'Rio Negro','department_id' =>68],
            ['name' => 'Rioblanco','department_id' =>73],
            ['name' => 'Riofrío','department_id' =>76],
            ['name' => 'Riohacha','department_id' =>44],
            ['name' => 'Risaralda','department_id' =>17],
            ['name' => 'Rivera','department_id' =>41],
            ['name' => 'Roberto Payán (San José)','department_id' =>52],
            ['name' => 'Roldanillo','department_id' =>76],
            ['name' => 'Roncesvalles','department_id' =>73],
            ['name' => 'Rondón','department_id' =>15],
            ['name' => 'Rosas','department_id' =>19],
            ['name' => 'Rovira','department_id' =>73],
            ['name' => 'Ráquira','department_id' =>15],
            ['name' => 'Río Iró','department_id' =>27],
            ['name' => 'Río Quito','department_id' =>27],
            ['name' => 'Río Sucio','department_id' =>17],
            ['name' => 'Río Viejo','department_id' =>13],
            ['name' => 'Río de oro','department_id' =>20],
            ['name' => 'Ríonegro','department_id' =>5],
            ['name' => 'Ríosucio','department_id' =>27],
            ['name' => 'Sabana de Torres','department_id' =>68],
            ['name' => 'Sabanagrande','department_id' =>8],
            ['name' => 'Sabanalarga','department_id' =>5],
            ['name' => 'Sabanalarga','department_id' =>8],
            ['name' => 'Sabanalarga','department_id' =>85],
            ['name' => 'Sabanas de San Angel (SAN ANGEL)','department_id' =>47],
            ['name' => 'Sabaneta','department_id' =>5],
            ['name' => 'Saboyá','department_id' =>15],
            ['name' => 'Sahagún','department_id' =>23],
            ['name' => 'Saladoblanco','department_id' =>41],
            ['name' => 'Salamina','department_id' =>17],
            ['name' => 'Salamina','department_id' =>47],
            ['name' => 'Salazar','department_id' =>54],
            ['name' => 'Saldaña','department_id' =>73],
            ['name' => 'Salento','department_id' =>63],
            ['name' => 'Salgar','department_id' =>5],
            ['name' => 'Samacá','department_id' =>15],
            ['name' => 'Samaniego','department_id' =>52],
            ['name' => 'Samaná','department_id' =>17],
            ['name' => 'Sampués','department_id' =>70],
            ['name' => 'San Agustín','department_id' =>41],
            ['name' => 'San Alberto','department_id' =>20],
            ['name' => 'San Andrés','department_id' =>68],
            ['name' => 'San Andrés Sotavento','department_id' =>23],
            ['name' => 'San Andrés de Cuerquía','department_id' =>5],
            ['name' => 'San Antero','department_id' =>23],
            ['name' => 'San Antonio','department_id' =>73],
            ['name' => 'San Antonio de Tequendama','department_id' =>25],
            ['name' => 'San Benito','department_id' =>68],
            ['name' => 'San Benito Abad','department_id' =>70],
            ['name' => 'San Bernardo','department_id' =>25],
            ['name' => 'San Bernardo','department_id' =>52],
            ['name' => 'San Bernardo del Viento','department_id' =>23],
            ['name' => 'San Calixto','department_id' =>54],
            ['name' => 'San Carlos','department_id' =>5],
            ['name' => 'San Carlos','department_id' =>23],
            ['name' => 'San Carlos de Guaroa','department_id' =>50],
            ['name' => 'San Cayetano','department_id' =>25],
            ['name' => 'San Cayetano','department_id' =>54],
            ['name' => 'San Cristobal','department_id' =>13],
            ['name' => 'San Diego','department_id' =>20],
            ['name' => 'San Eduardo','department_id' =>15],
            ['name' => 'San Estanislao','department_id' =>13],
            ['name' => 'San Fernando','department_id' =>13],
            ['name' => 'San Francisco','department_id' =>5],
            ['name' => 'San Francisco','department_id' =>25],
            ['name' => 'San Francisco','department_id' =>86],
            ['name' => 'San Gíl','department_id' =>68],
            ['name' => 'San Jacinto','department_id' =>13],
            ['name' => 'San Jacinto del Cauca','department_id' =>13],
            ['name' => 'San Jerónimo','department_id' =>5],
            ['name' => 'San Joaquín','department_id' =>68],
            ['name' => 'San José','department_id' =>17],
            ['name' => 'San José de Miranda','department_id' =>68],
            ['name' => 'San José de Montaña','department_id' =>5],
            ['name' => 'San José de Pare','department_id' =>15],
            ['name' => 'San José de Uré','department_id' =>23],
            ['name' => 'San José del Fragua','department_id' =>18],
            ['name' => 'San José del Guaviare','department_id' =>95],
            ['name' => 'San José del Palmar','department_id' =>27],
            ['name' => 'San Juan de Arama','department_id' =>50],
            ['name' => 'San Juan de Betulia','department_id' =>70],
            ['name' => 'San Juan de Nepomuceno','department_id' =>13],
            ['name' => 'San Juan de Pasto','department_id' =>52],
            ['name' => 'San Juan de Río Seco','department_id' =>25],
            ['name' => 'San Juan de Urabá','department_id' =>5],
            ['name' => 'San Juan del Cesar','department_id' =>44],
            ['name' => 'San Juanito','department_id' =>50],
            ['name' => 'San Lorenzo','department_id' =>52],
            ['name' => 'San Luis','department_id' =>73],
            ['name' => 'San Luís','department_id' =>5],
            ['name' => 'San Luís de Gaceno','department_id' =>15],
            ['name' => 'San Luís de Palenque','department_id' =>85],
            ['name' => 'San Marcos','department_id' =>70],
            ['name' => 'San Martín','department_id' =>20],
            ['name' => 'San Martín','department_id' =>50],
            ['name' => 'San Martín de Loba','department_id' =>13],
            ['name' => 'San Mateo','department_id' =>15],
            ['name' => 'San Miguel','department_id' =>68],
            ['name' => 'San Miguel','department_id' =>86],
            ['name' => 'San Miguel de Sema','department_id' =>15],
            ['name' => 'San Onofre','department_id' =>70],
            ['name' => 'San Pablo','department_id' =>13],
            ['name' => 'San Pablo','department_id' =>52],
            ['name' => 'San Pablo de Borbur','department_id' =>15],
            ['name' => 'San Pedro','department_id' =>5],
            ['name' => 'San Pedro','department_id' =>70],
            ['name' => 'San Pedro','department_id' =>76],
            ['name' => 'San Pedro de Cartago','department_id' =>52],
            ['name' => 'San Pedro de Urabá','department_id' =>5],
            ['name' => 'San Pelayo','department_id' =>23],
            ['name' => 'San Rafael','department_id' =>5],
            ['name' => 'San Roque','department_id' =>5],
            ['name' => 'San Sebastián','department_id' =>19],
            ['name' => 'San Sebastián de Buenavista','department_id' =>47],
            ['name' => 'San Vicente','department_id' =>5],
            ['name' => 'San Vicente del Caguán','department_id' =>18],
            ['name' => 'San Vicente del Chucurí','department_id' =>68],
            ['name' => 'San Zenón','department_id' =>47],
            ['name' => 'Sandoná','department_id' =>52],
            ['name' => 'Santa Ana','department_id' =>47],
            ['name' => 'Santa Bárbara','department_id' =>5],
            ['name' => 'Santa Bárbara','department_id' =>68],
            ['name' => 'Santa Bárbara (Iscuandé)','department_id' =>52],
            ['name' => 'Santa Bárbara de Pinto','department_id' =>47],
            ['name' => 'Santa Catalina','department_id' =>13],
            ['name' => 'Santa Fé de Antioquia','department_id' =>5],
            ['name' => 'Santa Genoveva de Docorodó','department_id' =>27],
            ['name' => 'Santa Helena del Opón','department_id' =>68],
            ['name' => 'Santa Isabel','department_id' =>73],
            ['name' => 'Santa Lucía','department_id' =>8],
            ['name' => 'Santa Marta','department_id' =>47],
            ['name' => 'Santa María','department_id' =>15],
            ['name' => 'Santa María','department_id' =>41],
            ['name' => 'Santa Rosa','department_id' =>13],
            ['name' => 'Santa Rosa','department_id' =>19],
            ['name' => 'Santa Rosa de Cabal','department_id' =>66],
            ['name' => 'Santa Rosa de Osos','department_id' =>5],
            ['name' => 'Santa Rosa de Viterbo','department_id' =>15],
            ['name' => 'Santa Rosa del Sur','department_id' =>13],
            ['name' => 'Santa Rosalía','department_id' =>99],
            ['name' => 'Santa Sofía','department_id' =>15],
            ['name' => 'Santana','department_id' =>15],
            ['name' => 'Santander de Quilichao','department_id' =>19],
            ['name' => 'Santiago','department_id' =>54],
            ['name' => 'Santiago','department_id' =>86],
            ['name' => 'Santo Domingo','department_id' =>5],
            ['name' => 'Santo Tomás','department_id' =>8],
            ['name' => 'Santuario','department_id' =>5],
            ['name' => 'Santuario','department_id' =>66],
            ['name' => 'Sapuyes','department_id' =>52],
            ['name' => 'Saravena','department_id' =>81],
            ['name' => 'Sardinata','department_id' =>54],
            ['name' => 'Sasaima','department_id' =>25],
            ['name' => 'Sativanorte','department_id' =>15],
            ['name' => 'Sativasur','department_id' =>15],
            ['name' => 'Segovia','department_id' =>5],
            ['name' => 'Sesquilé','department_id' =>25],
            ['name' => 'Sevilla','department_id' =>76],
            ['name' => 'Siachoque','department_id' =>15],
            ['name' => 'Sibaté','department_id' =>25],
            ['name' => 'Sibundoy','department_id' =>86],
            ['name' => 'Silos','department_id' =>54],
            ['name' => 'Silvania','department_id' =>25],
            ['name' => 'Silvia','department_id' =>19],
            ['name' => 'Simacota','department_id' =>68],
            ['name' => 'Simijaca','department_id' =>25],
            ['name' => 'Simití','department_id' =>13],
            ['name' => 'Sincelejo','department_id' =>70],
            ['name' => 'Sincé','department_id' =>70],
            ['name' => 'Sipí','department_id' =>27],
            ['name' => 'Sitionuevo','department_id' =>47],
            ['name' => 'Soacha','department_id' =>25],
            ['name' => 'Soatá','department_id' =>15],
            ['name' => 'Socha','department_id' =>15],
            ['name' => 'Socorro','department_id' =>68],
            ['name' => 'Socotá','department_id' =>15],
            ['name' => 'Sogamoso','department_id' =>15],
            ['name' => 'Solano','department_id' =>18],
            ['name' => 'Soledad','department_id' =>8],
            ['name' => 'Solita','department_id' =>18],
            ['name' => 'Somondoco','department_id' =>15],
            ['name' => 'Sonsón','department_id' =>5],
            ['name' => 'Sopetrán','department_id' =>5],
            ['name' => 'Soplaviento','department_id' =>13],
            ['name' => 'Sopó','department_id' =>25],
            ['name' => 'Sora','department_id' =>15],
            ['name' => 'Soracá','department_id' =>15],
            ['name' => 'Sotaquirá','department_id' =>15],
            ['name' => 'Sotara (Paispamba)','department_id' =>19],
            ['name' => 'Sotomayor (Los Andes)','department_id' =>52],
            ['name' => 'Suaita','department_id' =>68],
            ['name' => 'Suan','department_id' =>8],
            ['name' => 'Suaza','department_id' =>41],
            ['name' => 'Subachoque','department_id' =>25],
            ['name' => 'Sucre','department_id' =>19],
            ['name' => 'Sucre','department_id' =>68],
            ['name' => 'Sucre','department_id' =>70],
            ['name' => 'Suesca','department_id' =>25],
            ['name' => 'Supatá','department_id' =>25],
            ['name' => 'Supía','department_id' =>17],
            ['name' => 'Suratá','department_id' =>68],
            ['name' => 'Susa','department_id' =>25],
            ['name' => 'Susacón','department_id' =>15],
            ['name' => 'Sutamarchán','department_id' =>15],
            ['name' => 'Sutatausa','department_id' =>25],
            ['name' => 'Sutatenza','department_id' =>15],
            ['name' => 'Suárez','department_id' =>19],
            ['name' => 'Suárez','department_id' =>73],
            ['name' => 'Sácama','department_id' =>85],
            ['name' => 'Sáchica','department_id' =>15],
            ['name' => 'Tabio','department_id' =>25],
            ['name' => 'Tadó','department_id' =>27],
            ['name' => 'Talaigua Nuevo','department_id' =>13],
            ['name' => 'Tamalameque','department_id' =>20],
            ['name' => 'Tame','department_id' =>81],
            ['name' => 'Taminango','department_id' =>52],
            ['name' => 'Tangua','department_id' =>52],
            ['name' => 'Taraira','department_id' =>97],
            ['name' => 'Tarazá','department_id' =>5],
            ['name' => 'Tarqui','department_id' =>41],
            ['name' => 'Tarso','department_id' =>5],
            ['name' => 'Tasco','department_id' =>15],
            ['name' => 'Tauramena','department_id' =>85],
            ['name' => 'Tausa','department_id' =>25],
            ['name' => 'Tello','department_id' =>41],
            ['name' => 'Tena','department_id' =>25],
            ['name' => 'Tenerife','department_id' =>47],
            ['name' => 'Tenjo','department_id' =>25],
            ['name' => 'Tenza','department_id' =>15],
            ['name' => 'Teorama','department_id' =>54],
            ['name' => 'Teruel','department_id' =>41],
            ['name' => 'Tesalia','department_id' =>41],
            ['name' => 'Tibacuy','department_id' =>25],
            ['name' => 'Tibaná','department_id' =>15],
            ['name' => 'Tibasosa','department_id' =>15],
            ['name' => 'Tibirita','department_id' =>25],
            ['name' => 'Tibú','department_id' =>54],
            ['name' => 'Tierralta','department_id' =>23],
            ['name' => 'Timaná','department_id' =>41],
            ['name' => 'Timbiquí','department_id' =>19],
            ['name' => 'Timbío','department_id' =>19],
            ['name' => 'Tinjacá','department_id' =>15],
            ['name' => 'Tipacoque','department_id' =>15],
            ['name' => 'Tiquisio (Puerto Rico)','department_id' =>13],
            ['name' => 'Titiribí','department_id' =>5],
            ['name' => 'Toca','department_id' =>15],
            ['name' => 'Tocaima','department_id' =>25],
            ['name' => 'Tocancipá','department_id' =>25],
            ['name' => 'Toguí','department_id' =>15],
            ['name' => 'Toledo','department_id' =>5],
            ['name' => 'Toledo','department_id' =>54],
            ['name' => 'Tolú','department_id' =>70],
            ['name' => 'Tolú Viejo','department_id' =>70],
            ['name' => 'Tona','department_id' =>68],
            ['name' => 'Topagá','department_id' =>15],
            ['name' => 'Topaipí','department_id' =>25],
            ['name' => 'Toribío','department_id' =>19],
            ['name' => 'Toro','department_id' =>76],
            ['name' => 'Tota','department_id' =>15],
            ['name' => 'Totoró','department_id' =>19],
            ['name' => 'Trinidad','department_id' =>85],
            ['name' => 'Trujillo','department_id' =>76],
            ['name' => 'Tubará','department_id' =>8],
            ['name' => 'Tuchín','department_id' =>23],
            ['name' => 'Tulúa','department_id' =>76],
            ['name' => 'Tumaco','department_id' =>52],
            ['name' => 'Tunja','department_id' =>15],
            ['name' => 'Tunungua','department_id' =>15],
            ['name' => 'Turbaco','department_id' =>13],
            ['name' => 'Turbaná','department_id' =>13],
            ['name' => 'Turbo','department_id' =>5],
            ['name' => 'Turmequé','department_id' =>15],
            ['name' => 'Tuta','department_id' =>15],
            ['name' => 'Tutasá','department_id' =>15],
            ['name' => 'Támara','department_id' =>85],
            ['name' => 'Támesis','department_id' =>5],
            ['name' => 'Túquerres','department_id' =>52],
            ['name' => 'Ubalá','department_id' =>25],
            ['name' => 'Ubaque','department_id' =>25],
            ['name' => 'Ubaté','department_id' =>25],
            ['name' => 'Ulloa','department_id' =>76],
            ['name' => 'Une','department_id' =>25],
            ['name' => 'Unguía','department_id' =>27],
            ['name' => 'Unión Panamericana (ÁNIMAS)','department_id' =>27],
            ['name' => 'Uramita','department_id' =>5],
            ['name' => 'Uribe','department_id' =>50],
            ['name' => 'Uribia','department_id' =>44],
            ['name' => 'Urrao','department_id' =>5],
            ['name' => 'Urumita','department_id' =>44],
            ['name' => 'Usiacuri','department_id' =>8],
            ['name' => 'Valdivia','department_id' =>5],
            ['name' => 'Valencia','department_id' =>23],
            ['name' => 'Valle de San José','department_id' =>68],
            ['name' => 'Valle de San Juan','department_id' =>73],
            ['name' => 'Valle del Guamuez','department_id' =>86],
            ['name' => 'Valledupar','department_id' =>20],
            ['name' => 'Valparaiso','department_id' =>5],
            ['name' => 'Valparaiso','department_id' =>18],
            ['name' => 'Vegachí','department_id' =>5],
            ['name' => 'Venadillo','department_id' =>73],
            ['name' => 'Venecia','department_id' =>5],
            ['name' => 'Venecia (Ospina Pérez)','department_id' =>25],
            ['name' => 'Ventaquemada','department_id' =>15],
            ['name' => 'Vergara','department_id' =>25],
            ['name' => 'Versalles','department_id' =>76],
            ['name' => 'Vetas','department_id' =>68],
            ['name' => 'Viani','department_id' =>25],
            ['name' => 'Vigía del Fuerte','department_id' =>5],
            ['name' => 'Vijes','department_id' =>76],
            ['name' => 'Villa Caro','department_id' =>54],
            ['name' => 'Villa Rica','department_id' =>19],
            ['name' => 'Villa de Leiva','department_id' =>15],
            ['name' => 'Villa del Rosario','department_id' =>54],
            ['name' => 'Villagarzón','department_id' =>86],
            ['name' => 'Villagómez','department_id' =>25],
            ['name' => 'Villahermosa','department_id' =>73],
            ['name' => 'Villamaría','department_id' =>17],
            ['name' => 'Villanueva','department_id' =>13],
            ['name' => 'Villanueva','department_id' =>44],
            ['name' => 'Villanueva','department_id' =>68],
            ['name' => 'Villanueva','department_id' =>85],
            ['name' => 'Villapinzón','department_id' =>25],
            ['name' => 'Villarrica','department_id' =>73],
            ['name' => 'Villavicencio','department_id' =>50],
            ['name' => 'Villavieja','department_id' =>41],
            ['name' => 'Villeta','department_id' =>25],
            ['name' => 'Viotá','department_id' =>25],
            ['name' => 'Viracachá','department_id' =>15],
            ['name' => 'Vista Hermosa','department_id' =>50],
            ['name' => 'Viterbo','department_id' =>17],
            ['name' => 'Vélez','department_id' =>68],
            ['name' => 'Yacopí','department_id' =>25],
            ['name' => 'Yacuanquer','department_id' =>52],
            ['name' => 'Yaguará','department_id' =>41],
            ['name' => 'Yalí','department_id' =>5],
            ['name' => 'Yarumal','department_id' =>5],
            ['name' => 'Yolombó','department_id' =>5],
            ['name' => 'Yondó (Casabe)','department_id' =>5],
            ['name' => 'Yopal','department_id' =>85],
            ['name' => 'Yotoco','department_id' =>76],
            ['name' => 'Yumbo','department_id' =>76],
            ['name' => 'Zambrano','department_id' =>13],
            ['name' => 'Zapatoca','department_id' =>68],
            ['name' => 'Zapayán (PUNTA DE PIEDRAS)','department_id' =>47],
            ['name' => 'Zaragoza','department_id' =>5],
            ['name' => 'Zarzal','department_id' =>76],
            ['name' => 'Zetaquirá','department_id' =>15],
            ['name' => 'Zipacón','department_id' =>25],
            ['name' => 'Zipaquirá','department_id' =>25],
            ['name' => 'Zona Bananera (PRADO - SEVILLA)','department_id' =>47],
            ['name' => 'Ábrego','department_id' =>54],
            ['name' => 'Íquira','department_id' =>41],
            ['name' => 'Úmbita','department_id' =>15],
            ['name' => 'Útica','department_id' =>25],
        ];

        foreach ($cities as $city) {
            City::create($city);
        }
    }
} 